'use client';

import React from 'react';
import { LegalPageShell } from '@/components/layout/legal-page-shell';
import { BookOpen, Sparkles, CheckCircle2, AlertCircle } from 'lucide-react';

export default function AcademicIntegrityPage() {
  return (
    <LegalPageShell
      title="Academic Integrity & AI Policy"
      subtitle="Guidelines on ethical study collaboration, honor codes, and the use of AI tools on Elevare."
      lastUpdated="August 17, 2026"
    >
      <section className="space-y-8 text-slate-700 dark:text-slate-300">
        <div>
          <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white mb-3">
            1. Our Commitment to Honest Learning
          </h2>
          <p className="leading-relaxed">
            Elevare is built to empower students and learners through peer collaboration, organized note-taking, and productive study habits. Elevare is <strong>NOT</strong> a platform for academic cheating, plagiarism, or violating institutional honor codes.
          </p>
        </div>

        {/* AI Disclaimer Box */}
        <div className="p-5 rounded-2xl bg-purple-50 dark:bg-purple-950/40 border border-purple-200 dark:border-purple-800 text-purple-900 dark:text-purple-200 flex gap-4 items-start">
          <Sparkles className="w-6 h-6 text-purple-600 dark:text-purple-400 flex-shrink-0 mt-0.5" />
          <div className="text-xs sm:text-sm leading-relaxed">
            <strong className="text-purple-950 dark:text-purple-100 block mb-1">AI Summarization Feature Disclaimer:</strong>
            Elevare provides AI-assisted note summarization tools to help structure study materials. AI summaries are generated by automated language models and are provided for reference only. AI models may occasionally produce incorrect, incomplete, or inaccurate outputs (&quot;hallucinations&quot;). Users are solely responsible for reviewing and verifying the accuracy of their study notes and academic work.
          </div>
        </div>

        <div>
          <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white mb-3">
            2. Academic Integrity Guidelines
          </h2>
          <p className="leading-relaxed mb-4">
            When participating in study groups, sharing notes, or using whiteboards on Elevare, you agree to adhere to the following standards:
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="p-4 rounded-2xl bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-800 text-xs">
              <CheckCircle2 className="w-5 h-5 text-emerald-600 dark:text-emerald-400 mb-2" />
              <strong className="text-slate-900 dark:text-white block mb-1">Allowed & Encouraged</strong>
              <ul className="space-y-1 text-slate-600 dark:text-slate-300 list-disc pl-4">
                <li>Collaborative group note-taking</li>
                <li>Explaining difficult concepts to peers</li>
                <li>Brainstorming on shared whiteboards</li>
                <li>Summarizing lecture topics</li>
              </ul>
            </div>
            <div className="p-4 rounded-2xl bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-800 text-xs">
              <AlertCircle className="w-5 h-5 text-red-600 dark:text-red-400 mb-2" />
              <strong className="text-slate-900 dark:text-white block mb-1">Strictly Prohibited</strong>
              <ul className="space-y-1 text-slate-600 dark:text-slate-300 list-disc pl-4">
                <li>Sharing live exam answers or test keys</li>
                <li>Submitting others&apos; work as your own</li>
                <li>Distributing copyrighted test banks</li>
                <li>Soliciting homework completion for pay</li>
              </ul>
            </div>
          </div>
        </div>

        <div>
          <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white mb-3">
            3. Reporting Honor Code Violations
          </h2>
          <p className="leading-relaxed">
            If you encounter shared content or study group behavior that violates academic integrity standards or leaks live assessment materials, please use our built-in report feature or contact us at{' '}
            <a href="mailto:nantio.official@gmail.com" className="text-primary font-semibold hover:underline">
              nantio.official@gmail.com
            </a>.
          </p>
        </div>
      </section>
    </LegalPageShell>
  );
}
